-- Yummy menu replacement/update
-- Generated from the exported schema supplied by the user.
-- Prices are stored in poisha: 45000 = BDT 450.00.
-- This script updates/replaces only demo menu categories/products/translations.
-- It does NOT delete users, orders, settings, uploads, media, reservations or payments.

START TRANSACTION;

-- Remove old demo products that are no longer part of the new menu.
DELETE ct FROM `content_translations` ct INNER JOIN `products` p ON ct.`entity`='products' AND ct.`entity_id`=p.`id` WHERE p.`slug` IN ('shorshe-ilish','kacchi-for-two','family-kacchi','sharing-kala-bhuna','ilish-for-two','family-ilish');
DELETE FROM `products` WHERE `slug` IN ('shorshe-ilish','kacchi-for-two','family-kacchi','sharing-kala-bhuna','ilish-for-two','family-ilish');

-- Create/update menu categories and remember their IDs.
INSERT INTO `categories` (`name`,`slug`,`description`,`image`,`sort_order`) VALUES ('বিরিয়ানি ও তেহারি','biryani','সুগন্ধি চাল, মাংস ও মসলার ভরপুর আয়োজন','/assets/kacchi.png',0) ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`image`=VALUES(`image`),`sort_order`=VALUES(`sort_order`);
SET @cat_biryani=LAST_INSERT_ID();
INSERT INTO `categories` (`name`,`slug`,`description`,`image`,`sort_order`) VALUES ('স্ট্রিট ফুড','street-food','ফুচকা, চটপটি ও ঝালমুড়ির মতো জনপ্রিয় খাবার','',1) ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`image`=VALUES(`image`),`sort_order`=VALUES(`sort_order`);
SET @cat_street_food=LAST_INSERT_ID();
INSERT INTO `categories` (`name`,`slug`,`description`,`image`,`sort_order`) VALUES ('পিজ্জা','pizza','চিজ ও পছন্দের টপিংসে ওভেন-বেকড পিজ্জা','',2) ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`image`=VALUES(`image`),`sort_order`=VALUES(`sort_order`);
SET @cat_pizza=LAST_INSERT_ID();
INSERT INTO `categories` (`name`,`slug`,`description`,`image`,`sort_order`) VALUES ('শাওয়ারমা','shawarma','চিকেন ও বিফ শাওয়ারমার আয়োজন','',3) ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`image`=VALUES(`image`),`sort_order`=VALUES(`sort_order`);
SET @cat_shawarma=LAST_INSERT_ID();
INSERT INTO `categories` (`name`,`slug`,`description`,`image`,`sort_order`) VALUES ('বার্গার ও ফ্রাই','burger-fries','বার্গার, ফ্রেঞ্চ ফ্রাই ও ফাস্ট ফুড','',4) ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`image`=VALUES(`image`),`sort_order`=VALUES(`sort_order`);
SET @cat_burger_fries=LAST_INSERT_ID();
INSERT INTO `categories` (`name`,`slug`,`description`,`image`,`sort_order`) VALUES ('চিকেন','chicken','ফ্রাইড, গ্রিল ও দেশি স্টাইলে চিকেন','',5) ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`image`=VALUES(`image`),`sort_order`=VALUES(`sort_order`);
SET @cat_chicken=LAST_INSERT_ID();
INSERT INTO `categories` (`name`,`slug`,`description`,`image`,`sort_order`) VALUES ('বিফ','beef','কালা ভুনা, কারি ও কাবাবসহ বিফ আইটেম','/assets/kala-bhuna.png',6) ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`image`=VALUES(`image`),`sort_order`=VALUES(`sort_order`);
SET @cat_beef=LAST_INSERT_ID();
INSERT INTO `categories` (`name`,`slug`,`description`,`image`,`sort_order`) VALUES ('পরোটা ও সাইডস','paratha-sides','পরোটা ও খাবারের সাথে মানানসই সাইড আইটেম','',7) ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`image`=VALUES(`image`),`sort_order`=VALUES(`sort_order`);
SET @cat_paratha_sides=LAST_INSERT_ID();
INSERT INTO `categories` (`name`,`slug`,`description`,`image`,`sort_order`) VALUES ('অন্যান্য','others','নুডলস, পাস্তা, বোরহানি, লাচ্ছি ও আরও কিছু','',8) ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`image`=VALUES(`image`),`sort_order`=VALUES(`sort_order`);
SET @cat_others=LAST_INSERT_ID();

-- English translations for categories (Bangla remains the base content).
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('categories',@cat_biryani,'en','name','Biryani & Tehari') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('categories',@cat_biryani,'en','description','Aromatic rice dishes with meat and spices') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('categories',@cat_street_food,'en','name','Street Food') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('categories',@cat_street_food,'en','description','Popular favourites such as fuchka, chotpoti and jhal muri') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('categories',@cat_pizza,'en','name','Pizza') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('categories',@cat_pizza,'en','description','Oven-baked pizza with cheese and favourite toppings') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('categories',@cat_shawarma,'en','name','Shawarma') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('categories',@cat_shawarma,'en','description','Chicken and beef shawarma wraps') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('categories',@cat_burger_fries,'en','name','Burger & Fries') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('categories',@cat_burger_fries,'en','description','Burgers, french fries and fast-food favourites') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('categories',@cat_chicken,'en','name','Chicken') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('categories',@cat_chicken,'en','description','Fried, grilled and homestyle chicken dishes') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('categories',@cat_beef,'en','name','Beef') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('categories',@cat_beef,'en','description','Beef dishes including kala bhuna, curry and kebab') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('categories',@cat_paratha_sides,'en','name','Paratha & Sides') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('categories',@cat_paratha_sides,'en','description','Paratha and side dishes to complete your meal') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('categories',@cat_others,'en','name','Others') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('categories',@cat_others,'en','description','Noodles, pasta, borhani, lassi and more') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

-- Create/update products. Existing matching slugs are updated instead of duplicated.
INSERT INTO `products` (`category_id`,`name`,`slug`,`description`,`price`,`images`,`ingredients`,`preparation_minutes`,`available`,`featured`,`badge`,`sort_order`,`allergens`,`dietary`) VALUES (@cat_biryani,'কাচ্চি বিরিয়ানি','kacchi-biryani','<p>বাসমতি চাল, খাসির মাংস, আলু ও মসলায় দমে রান্না কাচ্চি।</p>',45000,'["\\/assets\\/kacchi.png"]','<p>চাল, খাসির মাংস, আলু, দই, ঘি, মসলা</p>',30,1,1,'জনপ্রিয়',0,'<p>দুধ ও দুগ্ধজাত উপাদান</p>','') ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`category_id`=VALUES(`category_id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`price`=VALUES(`price`),`images`=IF(`products`.`images`='[]' OR `products`.`images`='' ,VALUES(`images`),`products`.`images`),`ingredients`=VALUES(`ingredients`),`preparation_minutes`=VALUES(`preparation_minutes`),`available`=1,`featured`=VALUES(`featured`),`badge`=VALUES(`badge`),`sort_order`=VALUES(`sort_order`),`allergens`=VALUES(`allergens`),`dietary`=VALUES(`dietary`);
SET @prod_kacchi_biryani=LAST_INSERT_ID();
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_kacchi_biryani,'en','name','Kacchi Biryani') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_kacchi_biryani,'en','description','<p>Aromatic basmati rice cooked with mutton, potato and traditional spices.</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_kacchi_biryani,'en','ingredients','<p>Rice, mutton, potato, yogurt, ghee, spices</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_kacchi_biryani,'en','badge','Popular') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_kacchi_biryani,'en','allergens','<p>Contains dairy</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

INSERT INTO `products` (`category_id`,`name`,`slug`,`description`,`price`,`images`,`ingredients`,`preparation_minutes`,`available`,`featured`,`badge`,`sort_order`,`allergens`,`dietary`) VALUES (@cat_biryani,'বিফ তেহারি','beef-tehari','<p>সুগন্ধি চাল ও নরম গরুর মাংসে তৈরি ঝালঝাল তেহারি।</p>',30000,'[]','<p>চাল, গরুর মাংস, সরিষার তেল, মরিচ, মসলা</p>',25,1,0,'স্পেশাল',1,'<p>সরিষা থাকতে পারে</p>','') ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`category_id`=VALUES(`category_id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`price`=VALUES(`price`),`images`=IF(`products`.`images`='[]' OR `products`.`images`='' ,VALUES(`images`),`products`.`images`),`ingredients`=VALUES(`ingredients`),`preparation_minutes`=VALUES(`preparation_minutes`),`available`=1,`featured`=VALUES(`featured`),`badge`=VALUES(`badge`),`sort_order`=VALUES(`sort_order`),`allergens`=VALUES(`allergens`),`dietary`=VALUES(`dietary`);
SET @prod_beef_tehari=LAST_INSERT_ID();
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_tehari,'en','name','Beef Tehari') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_tehari,'en','description','<p>Fragrant rice cooked with tender beef and traditional spices.</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_tehari,'en','ingredients','<p>Rice, beef, mustard oil, chilli, spices</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_tehari,'en','badge','Special') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_tehari,'en','allergens','<p>May contain mustard</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

INSERT INTO `products` (`category_id`,`name`,`slug`,`description`,`price`,`images`,`ingredients`,`preparation_minutes`,`available`,`featured`,`badge`,`sort_order`,`allergens`,`dietary`) VALUES (@cat_street_food,'ফুচকা','fuchka','<p>মচমচে ফুচকা, আলু-ছোলা পুর, টক ও মসলার সাথে।</p>',12000,'[]','<p>ফুচকা, আলু, ছোলা, তেঁতুল, মসলা</p>',10,1,1,'১০ পিস',2,'<p>গম থাকতে পারে</p>','') ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`category_id`=VALUES(`category_id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`price`=VALUES(`price`),`images`=IF(`products`.`images`='[]' OR `products`.`images`='' ,VALUES(`images`),`products`.`images`),`ingredients`=VALUES(`ingredients`),`preparation_minutes`=VALUES(`preparation_minutes`),`available`=1,`featured`=VALUES(`featured`),`badge`=VALUES(`badge`),`sort_order`=VALUES(`sort_order`),`allergens`=VALUES(`allergens`),`dietary`=VALUES(`dietary`);
SET @prod_fuchka=LAST_INSERT_ID();
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_fuchka,'en','name','Fuchka') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_fuchka,'en','description','<p>Crispy fuchka filled with potato and chickpeas, served with tangy tamarind water.</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_fuchka,'en','ingredients','<p>Fuchka shells, potato, chickpeas, tamarind, spices</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_fuchka,'en','badge','10 pieces') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_fuchka,'en','allergens','<p>Contains wheat</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

INSERT INTO `products` (`category_id`,`name`,`slug`,`description`,`price`,`images`,`ingredients`,`preparation_minutes`,`available`,`featured`,`badge`,`sort_order`,`allergens`,`dietary`) VALUES (@cat_street_food,'চটপটি','chotpoti','<p>ছোলা, আলু, ডিম, তেঁতুল ও মসলায় তৈরি জনপ্রিয় চটপটি।</p>',13000,'[]','<p>ছোলা, আলু, ডিম, তেঁতুল, মসলা</p>',12,1,0,'স্ট্রিট ফুড',3,'<p>ডিম থাকতে পারে</p>','') ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`category_id`=VALUES(`category_id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`price`=VALUES(`price`),`images`=IF(`products`.`images`='[]' OR `products`.`images`='' ,VALUES(`images`),`products`.`images`),`ingredients`=VALUES(`ingredients`),`preparation_minutes`=VALUES(`preparation_minutes`),`available`=1,`featured`=VALUES(`featured`),`badge`=VALUES(`badge`),`sort_order`=VALUES(`sort_order`),`allergens`=VALUES(`allergens`),`dietary`=VALUES(`dietary`);
SET @prod_chotpoti=LAST_INSERT_ID();
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chotpoti,'en','name','Chotpoti') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chotpoti,'en','description','<p>A popular street-food bowl with chickpeas, potato, egg, tamarind and spices.</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chotpoti,'en','ingredients','<p>Chickpeas, potato, egg, tamarind, spices</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chotpoti,'en','badge','Street food') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chotpoti,'en','allergens','<p>May contain egg</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

INSERT INTO `products` (`category_id`,`name`,`slug`,`description`,`price`,`images`,`ingredients`,`preparation_minutes`,`available`,`featured`,`badge`,`sort_order`,`allergens`,`dietary`) VALUES (@cat_street_food,'ঝালমুড়ি','jhal-muri','<p>মুড়ি, পেঁয়াজ, কাঁচামরিচ, সরিষার তেল ও মসলার মিশ্রণ।</p>',8000,'[]','<p>মুড়ি, পেঁয়াজ, কাঁচামরিচ, সরিষার তেল, মসলা</p>',8,1,0,'ঝাল',4,'<p>সরিষা থাকতে পারে</p>','') ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`category_id`=VALUES(`category_id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`price`=VALUES(`price`),`images`=IF(`products`.`images`='[]' OR `products`.`images`='' ,VALUES(`images`),`products`.`images`),`ingredients`=VALUES(`ingredients`),`preparation_minutes`=VALUES(`preparation_minutes`),`available`=1,`featured`=VALUES(`featured`),`badge`=VALUES(`badge`),`sort_order`=VALUES(`sort_order`),`allergens`=VALUES(`allergens`),`dietary`=VALUES(`dietary`);
SET @prod_jhal_muri=LAST_INSERT_ID();
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_jhal_muri,'en','name','Jhal Muri') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_jhal_muri,'en','description','<p>Puffed rice tossed with onion, green chilli, mustard oil and spices.</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_jhal_muri,'en','ingredients','<p>Puffed rice, onion, green chilli, mustard oil, spices</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_jhal_muri,'en','badge','Spicy') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_jhal_muri,'en','allergens','<p>May contain mustard</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

INSERT INTO `products` (`category_id`,`name`,`slug`,`description`,`price`,`images`,`ingredients`,`preparation_minutes`,`available`,`featured`,`badge`,`sort_order`,`allergens`,`dietary`) VALUES (@cat_pizza,'চিকেন পিজ্জা','chicken-pizza','<p>চিকেন, চিজ ও সস দিয়ে তৈরি ওভেন-বেকড পিজ্জা।</p>',45000,'[]','<p>পিজ্জা ডো, চিকেন, চিজ, সস</p>',25,1,1,'মিডিয়াম',5,'<p>গম ও দুধ</p>','') ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`category_id`=VALUES(`category_id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`price`=VALUES(`price`),`images`=IF(`products`.`images`='[]' OR `products`.`images`='' ,VALUES(`images`),`products`.`images`),`ingredients`=VALUES(`ingredients`),`preparation_minutes`=VALUES(`preparation_minutes`),`available`=1,`featured`=VALUES(`featured`),`badge`=VALUES(`badge`),`sort_order`=VALUES(`sort_order`),`allergens`=VALUES(`allergens`),`dietary`=VALUES(`dietary`);
SET @prod_chicken_pizza=LAST_INSERT_ID();
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_pizza,'en','name','Chicken Pizza') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_pizza,'en','description','<p>Oven-baked pizza topped with chicken, cheese and sauce.</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_pizza,'en','ingredients','<p>Pizza dough, chicken, cheese, sauce</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_pizza,'en','badge','Medium') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_pizza,'en','allergens','<p>Contains wheat and dairy</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

INSERT INTO `products` (`category_id`,`name`,`slug`,`description`,`price`,`images`,`ingredients`,`preparation_minutes`,`available`,`featured`,`badge`,`sort_order`,`allergens`,`dietary`) VALUES (@cat_pizza,'বিফ পিজ্জা','beef-pizza','<p>বিফ, চিজ, পেঁয়াজ ও সসের টপিংসে পিজ্জা।</p>',65000,'[]','<p>পিজ্জা ডো, বিফ, চিজ, পেঁয়াজ, সস</p>',25,1,0,'মিডিয়াম',6,'<p>গম ও দুধ</p>','') ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`category_id`=VALUES(`category_id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`price`=VALUES(`price`),`images`=IF(`products`.`images`='[]' OR `products`.`images`='' ,VALUES(`images`),`products`.`images`),`ingredients`=VALUES(`ingredients`),`preparation_minutes`=VALUES(`preparation_minutes`),`available`=1,`featured`=VALUES(`featured`),`badge`=VALUES(`badge`),`sort_order`=VALUES(`sort_order`),`allergens`=VALUES(`allergens`),`dietary`=VALUES(`dietary`);
SET @prod_beef_pizza=LAST_INSERT_ID();
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_pizza,'en','name','Beef Pizza') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_pizza,'en','description','<p>Pizza topped with seasoned beef, cheese, onion and sauce.</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_pizza,'en','ingredients','<p>Pizza dough, beef, cheese, onion, sauce</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_pizza,'en','badge','Medium') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_pizza,'en','allergens','<p>Contains wheat and dairy</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

INSERT INTO `products` (`category_id`,`name`,`slug`,`description`,`price`,`images`,`ingredients`,`preparation_minutes`,`available`,`featured`,`badge`,`sort_order`,`allergens`,`dietary`) VALUES (@cat_shawarma,'চিকেন শাওয়ারমা','chicken-shawarma','<p>মেরিনেট করা চিকেন, সবজি ও সসের র‍্যাপ।</p>',22000,'[]','<p>রুটি, চিকেন, বাঁধাকপি, শসা, সস</p>',15,1,1,'বেস্ট সেলার',7,'<p>গম, ডিম ও দুধ থাকতে পারে</p>','') ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`category_id`=VALUES(`category_id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`price`=VALUES(`price`),`images`=IF(`products`.`images`='[]' OR `products`.`images`='' ,VALUES(`images`),`products`.`images`),`ingredients`=VALUES(`ingredients`),`preparation_minutes`=VALUES(`preparation_minutes`),`available`=1,`featured`=VALUES(`featured`),`badge`=VALUES(`badge`),`sort_order`=VALUES(`sort_order`),`allergens`=VALUES(`allergens`),`dietary`=VALUES(`dietary`);
SET @prod_chicken_shawarma=LAST_INSERT_ID();
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_shawarma,'en','name','Chicken Shawarma') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_shawarma,'en','description','<p>A wrap filled with marinated chicken, vegetables and creamy sauce.</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_shawarma,'en','ingredients','<p>Flatbread, chicken, cabbage, cucumber, sauce</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_shawarma,'en','badge','Best seller') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_shawarma,'en','allergens','<p>May contain wheat, egg and dairy</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

INSERT INTO `products` (`category_id`,`name`,`slug`,`description`,`price`,`images`,`ingredients`,`preparation_minutes`,`available`,`featured`,`badge`,`sort_order`,`allergens`,`dietary`) VALUES (@cat_shawarma,'বিফ শাওয়ারমা','beef-shawarma','<p>মসলাদার বিফ, সবজি ও সসের শাওয়ারমা র‍্যাপ।</p>',26000,'[]','<p>রুটি, বিফ, সবজি, সস</p>',15,1,0,'রেগুলার',8,'<p>গম, ডিম ও দুধ থাকতে পারে</p>','') ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`category_id`=VALUES(`category_id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`price`=VALUES(`price`),`images`=IF(`products`.`images`='[]' OR `products`.`images`='' ,VALUES(`images`),`products`.`images`),`ingredients`=VALUES(`ingredients`),`preparation_minutes`=VALUES(`preparation_minutes`),`available`=1,`featured`=VALUES(`featured`),`badge`=VALUES(`badge`),`sort_order`=VALUES(`sort_order`),`allergens`=VALUES(`allergens`),`dietary`=VALUES(`dietary`);
SET @prod_beef_shawarma=LAST_INSERT_ID();
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_shawarma,'en','name','Beef Shawarma') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_shawarma,'en','description','<p>Shawarma wrap with seasoned beef, vegetables and sauce.</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_shawarma,'en','ingredients','<p>Flatbread, beef, vegetables, sauce</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_shawarma,'en','badge','Regular') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_shawarma,'en','allergens','<p>May contain wheat, egg and dairy</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

INSERT INTO `products` (`category_id`,`name`,`slug`,`description`,`price`,`images`,`ingredients`,`preparation_minutes`,`available`,`featured`,`badge`,`sort_order`,`allergens`,`dietary`) VALUES (@cat_burger_fries,'চিকেন বার্গার','chicken-burger','<p>ক্রিসপি চিকেন প্যাটি, সবজি ও সসসহ নরম বান।</p>',25000,'[]','<p>বান, চিকেন, লেটুস, সস</p>',15,1,1,'ক্রিসপি',9,'<p>গম, ডিম ও দুধ থাকতে পারে</p>','') ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`category_id`=VALUES(`category_id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`price`=VALUES(`price`),`images`=IF(`products`.`images`='[]' OR `products`.`images`='' ,VALUES(`images`),`products`.`images`),`ingredients`=VALUES(`ingredients`),`preparation_minutes`=VALUES(`preparation_minutes`),`available`=1,`featured`=VALUES(`featured`),`badge`=VALUES(`badge`),`sort_order`=VALUES(`sort_order`),`allergens`=VALUES(`allergens`),`dietary`=VALUES(`dietary`);
SET @prod_chicken_burger=LAST_INSERT_ID();
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_burger,'en','name','Chicken Burger') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_burger,'en','description','<p>Soft bun with crispy chicken patty, vegetables and sauce.</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_burger,'en','ingredients','<p>Bun, chicken, lettuce, sauce</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_burger,'en','badge','Crispy') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_burger,'en','allergens','<p>May contain wheat, egg and dairy</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

INSERT INTO `products` (`category_id`,`name`,`slug`,`description`,`price`,`images`,`ingredients`,`preparation_minutes`,`available`,`featured`,`badge`,`sort_order`,`allergens`,`dietary`) VALUES (@cat_burger_fries,'বিফ বার্গার','beef-burger','<p>বিফ প্যাটি, চিজ, সবজি ও সসসহ বার্গার।</p>',28000,'[]','<p>বান, বিফ প্যাটি, চিজ, সবজি, সস</p>',15,1,0,'চিজি',10,'<p>গম, ডিম ও দুধ থাকতে পারে</p>','') ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`category_id`=VALUES(`category_id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`price`=VALUES(`price`),`images`=IF(`products`.`images`='[]' OR `products`.`images`='' ,VALUES(`images`),`products`.`images`),`ingredients`=VALUES(`ingredients`),`preparation_minutes`=VALUES(`preparation_minutes`),`available`=1,`featured`=VALUES(`featured`),`badge`=VALUES(`badge`),`sort_order`=VALUES(`sort_order`),`allergens`=VALUES(`allergens`),`dietary`=VALUES(`dietary`);
SET @prod_beef_burger=LAST_INSERT_ID();
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_burger,'en','name','Beef Burger') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_burger,'en','description','<p>Beef patty burger with cheese, vegetables and sauce.</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_burger,'en','ingredients','<p>Bun, beef patty, cheese, vegetables, sauce</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_burger,'en','badge','Cheesy') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_burger,'en','allergens','<p>May contain wheat, egg and dairy</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

INSERT INTO `products` (`category_id`,`name`,`slug`,`description`,`price`,`images`,`ingredients`,`preparation_minutes`,`available`,`featured`,`badge`,`sort_order`,`allergens`,`dietary`) VALUES (@cat_burger_fries,'ফ্রেঞ্চ ফ্রাই','french-fries','<p>সোনালি ও মচমচে আলুর ফ্রাই।</p>',15000,'[]','<p>আলু, তেল, লবণ</p>',10,1,0,'ক্রিসপি',11,'<p>একই রান্নাঘরে সাধারণ অ্যালার্জেন ব্যবহার হয়</p>','') ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`category_id`=VALUES(`category_id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`price`=VALUES(`price`),`images`=IF(`products`.`images`='[]' OR `products`.`images`='' ,VALUES(`images`),`products`.`images`),`ingredients`=VALUES(`ingredients`),`preparation_minutes`=VALUES(`preparation_minutes`),`available`=1,`featured`=VALUES(`featured`),`badge`=VALUES(`badge`),`sort_order`=VALUES(`sort_order`),`allergens`=VALUES(`allergens`),`dietary`=VALUES(`dietary`);
SET @prod_french_fries=LAST_INSERT_ID();
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_french_fries,'en','name','French Fries') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_french_fries,'en','description','<p>Golden and crispy potato fries.</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_french_fries,'en','ingredients','<p>Potato, oil, salt</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_french_fries,'en','badge','Crispy') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_french_fries,'en','allergens','<p>Prepared in a kitchen that handles common allergens</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

INSERT INTO `products` (`category_id`,`name`,`slug`,`description`,`price`,`images`,`ingredients`,`preparation_minutes`,`available`,`featured`,`badge`,`sort_order`,`allergens`,`dietary`) VALUES (@cat_chicken,'ফ্রাইড চিকেন','fried-chicken','<p>মচমচে কোটিংসহ জুসি ফ্রাইড চিকেন।</p>',18000,'[]','<p>চিকেন, ময়দা, ডিম, মসলা</p>',18,1,1,'১ পিস',12,'<p>গম ও ডিম</p>','') ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`category_id`=VALUES(`category_id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`price`=VALUES(`price`),`images`=IF(`products`.`images`='[]' OR `products`.`images`='' ,VALUES(`images`),`products`.`images`),`ingredients`=VALUES(`ingredients`),`preparation_minutes`=VALUES(`preparation_minutes`),`available`=1,`featured`=VALUES(`featured`),`badge`=VALUES(`badge`),`sort_order`=VALUES(`sort_order`),`allergens`=VALUES(`allergens`),`dietary`=VALUES(`dietary`);
SET @prod_fried_chicken=LAST_INSERT_ID();
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_fried_chicken,'en','name','Fried Chicken') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_fried_chicken,'en','description','<p>Juicy fried chicken with a crispy seasoned coating.</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_fried_chicken,'en','ingredients','<p>Chicken, flour, egg, spices</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_fried_chicken,'en','badge','1 piece') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_fried_chicken,'en','allergens','<p>Contains wheat and egg</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

INSERT INTO `products` (`category_id`,`name`,`slug`,`description`,`price`,`images`,`ingredients`,`preparation_minutes`,`available`,`featured`,`badge`,`sort_order`,`allergens`,`dietary`) VALUES (@cat_chicken,'চিকেন গ্রিল','chicken-grill','<p>মসলায় মেরিনেট করা গ্রিলড চিকেন।</p>',35000,'[]','<p>চিকেন, দই, মসলা, তেল</p>',25,1,0,'হাফ',13,'<p>দুধ থাকতে পারে</p>','') ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`category_id`=VALUES(`category_id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`price`=VALUES(`price`),`images`=IF(`products`.`images`='[]' OR `products`.`images`='' ,VALUES(`images`),`products`.`images`),`ingredients`=VALUES(`ingredients`),`preparation_minutes`=VALUES(`preparation_minutes`),`available`=1,`featured`=VALUES(`featured`),`badge`=VALUES(`badge`),`sort_order`=VALUES(`sort_order`),`allergens`=VALUES(`allergens`),`dietary`=VALUES(`dietary`);
SET @prod_chicken_grill=LAST_INSERT_ID();
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_grill,'en','name','Chicken Grill') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_grill,'en','description','<p>Chicken marinated with spices and grilled until tender.</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_grill,'en','ingredients','<p>Chicken, yogurt, spices, oil</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_grill,'en','badge','Half portion') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_grill,'en','allergens','<p>May contain dairy</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

INSERT INTO `products` (`category_id`,`name`,`slug`,`description`,`price`,`images`,`ingredients`,`preparation_minutes`,`available`,`featured`,`badge`,`sort_order`,`allergens`,`dietary`) VALUES (@cat_chicken,'চিকেন কারি','chicken-curry','<p>দেশি মসলায় রান্না করা ঘরোয়া চিকেন কারি।</p>',28000,'[]','<p>চিকেন, পেঁয়াজ, তেল, মসলা</p>',25,1,0,'১ জনের জন্য',14,'<p>একই রান্নাঘরে সাধারণ অ্যালার্জেন ব্যবহার হয়</p>','') ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`category_id`=VALUES(`category_id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`price`=VALUES(`price`),`images`=IF(`products`.`images`='[]' OR `products`.`images`='' ,VALUES(`images`),`products`.`images`),`ingredients`=VALUES(`ingredients`),`preparation_minutes`=VALUES(`preparation_minutes`),`available`=1,`featured`=VALUES(`featured`),`badge`=VALUES(`badge`),`sort_order`=VALUES(`sort_order`),`allergens`=VALUES(`allergens`),`dietary`=VALUES(`dietary`);
SET @prod_chicken_curry=LAST_INSERT_ID();
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_curry,'en','name','Chicken Curry') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_curry,'en','description','<p>Homestyle chicken curry cooked with Bangladeshi spices.</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_curry,'en','ingredients','<p>Chicken, onion, oil, spices</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_curry,'en','badge','Single serving') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_curry,'en','allergens','<p>Prepared in a kitchen that handles common allergens</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

INSERT INTO `products` (`category_id`,`name`,`slug`,`description`,`price`,`images`,`ingredients`,`preparation_minutes`,`available`,`featured`,`badge`,`sort_order`,`allergens`,`dietary`) VALUES (@cat_beef,'কালা ভুনা','kala-bhuna','<p>পেঁয়াজ ও দেশি মসলায় ধীরে রান্না করা চট্টগ্রামের বিখ্যাত বিফ কালা ভুনা।</p>',38000,'["\\/assets\\/kala-bhuna.png"]','<p>গরুর মাংস, পেঁয়াজ, তেল, মসলা</p>',30,1,0,'দেশি স্বাদ',15,'<p>একই রান্নাঘরে সাধারণ অ্যালার্জেন ব্যবহার হয়</p>','') ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`category_id`=VALUES(`category_id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`price`=VALUES(`price`),`images`=IF(`products`.`images`='[]' OR `products`.`images`='' ,VALUES(`images`),`products`.`images`),`ingredients`=VALUES(`ingredients`),`preparation_minutes`=VALUES(`preparation_minutes`),`available`=1,`featured`=VALUES(`featured`),`badge`=VALUES(`badge`),`sort_order`=VALUES(`sort_order`),`allergens`=VALUES(`allergens`),`dietary`=VALUES(`dietary`);
SET @prod_kala_bhuna=LAST_INSERT_ID();
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_kala_bhuna,'en','name','Beef Kala Bhuna') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_kala_bhuna,'en','description','<p>Chattogram-style beef slow-cooked with onion and traditional spices.</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_kala_bhuna,'en','ingredients','<p>Beef, onion, oil, spices</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_kala_bhuna,'en','badge','Local favourite') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_kala_bhuna,'en','allergens','<p>Prepared in a kitchen that handles common allergens</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

INSERT INTO `products` (`category_id`,`name`,`slug`,`description`,`price`,`images`,`ingredients`,`preparation_minutes`,`available`,`featured`,`badge`,`sort_order`,`allergens`,`dietary`) VALUES (@cat_beef,'বিফ কারি','beef-curry','<p>নরম গরুর মাংস ও ঘন মসলার ঝোল।</p>',32000,'[]','<p>গরুর মাংস, পেঁয়াজ, তেল, মসলা</p>',30,1,0,'১ জনের জন্য',16,'<p>একই রান্নাঘরে সাধারণ অ্যালার্জেন ব্যবহার হয়</p>','') ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`category_id`=VALUES(`category_id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`price`=VALUES(`price`),`images`=IF(`products`.`images`='[]' OR `products`.`images`='' ,VALUES(`images`),`products`.`images`),`ingredients`=VALUES(`ingredients`),`preparation_minutes`=VALUES(`preparation_minutes`),`available`=1,`featured`=VALUES(`featured`),`badge`=VALUES(`badge`),`sort_order`=VALUES(`sort_order`),`allergens`=VALUES(`allergens`),`dietary`=VALUES(`dietary`);
SET @prod_beef_curry=LAST_INSERT_ID();
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_curry,'en','name','Beef Curry') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_curry,'en','description','<p>Tender beef cooked in a rich spiced curry.</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_curry,'en','ingredients','<p>Beef, onion, oil, spices</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_curry,'en','badge','Single serving') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_curry,'en','allergens','<p>Prepared in a kitchen that handles common allergens</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

INSERT INTO `products` (`category_id`,`name`,`slug`,`description`,`price`,`images`,`ingredients`,`preparation_minutes`,`available`,`featured`,`badge`,`sort_order`,`allergens`,`dietary`) VALUES (@cat_beef,'বিফ কাবাব','beef-kebab','<p>মসলাদার বিফ কাবাব, স্ন্যাক বা সাইড হিসেবে উপযুক্ত।</p>',25000,'[]','<p>বিফ, পেঁয়াজ, মসলা</p>',20,1,0,'২ পিস',17,'<p>একই রান্নাঘরে সাধারণ অ্যালার্জেন ব্যবহার হয়</p>','') ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`category_id`=VALUES(`category_id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`price`=VALUES(`price`),`images`=IF(`products`.`images`='[]' OR `products`.`images`='' ,VALUES(`images`),`products`.`images`),`ingredients`=VALUES(`ingredients`),`preparation_minutes`=VALUES(`preparation_minutes`),`available`=1,`featured`=VALUES(`featured`),`badge`=VALUES(`badge`),`sort_order`=VALUES(`sort_order`),`allergens`=VALUES(`allergens`),`dietary`=VALUES(`dietary`);
SET @prod_beef_kebab=LAST_INSERT_ID();
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_kebab,'en','name','Beef Kebab') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_kebab,'en','description','<p>Seasoned beef kebab, perfect as a snack or side.</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_kebab,'en','ingredients','<p>Beef, onion, spices</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_kebab,'en','badge','2 pieces') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_beef_kebab,'en','allergens','<p>Prepared in a kitchen that handles common allergens</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

INSERT INTO `products` (`category_id`,`name`,`slug`,`description`,`price`,`images`,`ingredients`,`preparation_minutes`,`available`,`featured`,`badge`,`sort_order`,`allergens`,`dietary`) VALUES (@cat_paratha_sides,'প্লেইন পরোটা','plain-paratha','<p>তাওয়ায় সেঁকা নরম ও লেয়ারড পরোটা।</p>',4000,'[]','<p>ময়দা, তেল, লবণ</p>',8,1,0,'১ পিস',18,'<p>গম</p>','') ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`category_id`=VALUES(`category_id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`price`=VALUES(`price`),`images`=IF(`products`.`images`='[]' OR `products`.`images`='' ,VALUES(`images`),`products`.`images`),`ingredients`=VALUES(`ingredients`),`preparation_minutes`=VALUES(`preparation_minutes`),`available`=1,`featured`=VALUES(`featured`),`badge`=VALUES(`badge`),`sort_order`=VALUES(`sort_order`),`allergens`=VALUES(`allergens`),`dietary`=VALUES(`dietary`);
SET @prod_plain_paratha=LAST_INSERT_ID();
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_plain_paratha,'en','name','Plain Paratha') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_plain_paratha,'en','description','<p>Soft layered paratha cooked on a griddle.</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_plain_paratha,'en','ingredients','<p>Flour, oil, salt</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_plain_paratha,'en','badge','1 piece') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_plain_paratha,'en','allergens','<p>Contains wheat</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

INSERT INTO `products` (`category_id`,`name`,`slug`,`description`,`price`,`images`,`ingredients`,`preparation_minutes`,`available`,`featured`,`badge`,`sort_order`,`allergens`,`dietary`) VALUES (@cat_paratha_sides,'ডিম পরোটা','egg-paratha','<p>পরোটার সাথে ডিমের সহজ ও মজাদার কম্বিনেশন।</p>',8000,'[]','<p>ময়দা, ডিম, তেল, মসলা</p>',10,1,0,'১ পিস',19,'<p>গম ও ডিম</p>','') ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`category_id`=VALUES(`category_id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`price`=VALUES(`price`),`images`=IF(`products`.`images`='[]' OR `products`.`images`='' ,VALUES(`images`),`products`.`images`),`ingredients`=VALUES(`ingredients`),`preparation_minutes`=VALUES(`preparation_minutes`),`available`=1,`featured`=VALUES(`featured`),`badge`=VALUES(`badge`),`sort_order`=VALUES(`sort_order`),`allergens`=VALUES(`allergens`),`dietary`=VALUES(`dietary`);
SET @prod_egg_paratha=LAST_INSERT_ID();
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_egg_paratha,'en','name','Egg Paratha') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_egg_paratha,'en','description','<p>A simple and tasty combination of paratha and egg.</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_egg_paratha,'en','ingredients','<p>Flour, egg, oil, spices</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_egg_paratha,'en','badge','1 piece') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_egg_paratha,'en','allergens','<p>Contains wheat and egg</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

INSERT INTO `products` (`category_id`,`name`,`slug`,`description`,`price`,`images`,`ingredients`,`preparation_minutes`,`available`,`featured`,`badge`,`sort_order`,`allergens`,`dietary`) VALUES (@cat_paratha_sides,'মোগলাই পরোটা','mughlai-paratha','<p>ডিম, কিমা ও মসলার পুরভরা মচমচে মোগলাই পরোটা।</p>',18000,'[]','<p>ময়দা, ডিম, কিমা, পেঁয়াজ, মসলা</p>',18,1,0,'স্পেশাল',20,'<p>গম ও ডিম</p>','') ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`category_id`=VALUES(`category_id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`price`=VALUES(`price`),`images`=IF(`products`.`images`='[]' OR `products`.`images`='' ,VALUES(`images`),`products`.`images`),`ingredients`=VALUES(`ingredients`),`preparation_minutes`=VALUES(`preparation_minutes`),`available`=1,`featured`=VALUES(`featured`),`badge`=VALUES(`badge`),`sort_order`=VALUES(`sort_order`),`allergens`=VALUES(`allergens`),`dietary`=VALUES(`dietary`);
SET @prod_mughlai_paratha=LAST_INSERT_ID();
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_mughlai_paratha,'en','name','Mughlai Paratha') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_mughlai_paratha,'en','description','<p>Crispy paratha stuffed with egg, minced meat and spices.</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_mughlai_paratha,'en','ingredients','<p>Flour, egg, minced meat, onion, spices</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_mughlai_paratha,'en','badge','Special') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_mughlai_paratha,'en','allergens','<p>Contains wheat and egg</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

INSERT INTO `products` (`category_id`,`name`,`slug`,`description`,`price`,`images`,`ingredients`,`preparation_minutes`,`available`,`featured`,`badge`,`sort_order`,`allergens`,`dietary`) VALUES (@cat_others,'চিকেন নুডলস','chicken-noodles','<p>চিকেন ও সবজি দিয়ে স্টির-ফ্রাইড নুডলস।</p>',20000,'[]','<p>নুডলস, চিকেন, সবজি, সস</p>',18,1,0,'রেগুলার',21,'<p>গম, সয়া ও ডিম থাকতে পারে</p>','') ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`category_id`=VALUES(`category_id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`price`=VALUES(`price`),`images`=IF(`products`.`images`='[]' OR `products`.`images`='' ,VALUES(`images`),`products`.`images`),`ingredients`=VALUES(`ingredients`),`preparation_minutes`=VALUES(`preparation_minutes`),`available`=1,`featured`=VALUES(`featured`),`badge`=VALUES(`badge`),`sort_order`=VALUES(`sort_order`),`allergens`=VALUES(`allergens`),`dietary`=VALUES(`dietary`);
SET @prod_chicken_noodles=LAST_INSERT_ID();
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_noodles,'en','name','Chicken Noodles') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_noodles,'en','description','<p>Stir-fried noodles with chicken and vegetables.</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_noodles,'en','ingredients','<p>Noodles, chicken, vegetables, sauce</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_noodles,'en','badge','Regular') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_noodles,'en','allergens','<p>May contain wheat, soy and egg</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

INSERT INTO `products` (`category_id`,`name`,`slug`,`description`,`price`,`images`,`ingredients`,`preparation_minutes`,`available`,`featured`,`badge`,`sort_order`,`allergens`,`dietary`) VALUES (@cat_others,'চিকেন পাস্তা','chicken-pasta','<p>চিকেন ও ক্রিমি সসে রান্না করা পাস্তা।</p>',25000,'[]','<p>পাস্তা, চিকেন, ক্রিম, চিজ, মসলা</p>',20,1,0,'ক্রিমি',22,'<p>গম ও দুধ</p>','') ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`category_id`=VALUES(`category_id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`price`=VALUES(`price`),`images`=IF(`products`.`images`='[]' OR `products`.`images`='' ,VALUES(`images`),`products`.`images`),`ingredients`=VALUES(`ingredients`),`preparation_minutes`=VALUES(`preparation_minutes`),`available`=1,`featured`=VALUES(`featured`),`badge`=VALUES(`badge`),`sort_order`=VALUES(`sort_order`),`allergens`=VALUES(`allergens`),`dietary`=VALUES(`dietary`);
SET @prod_chicken_pasta=LAST_INSERT_ID();
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_pasta,'en','name','Chicken Pasta') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_pasta,'en','description','<p>Pasta with chicken in a creamy sauce.</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_pasta,'en','ingredients','<p>Pasta, chicken, cream, cheese, spices</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_pasta,'en','badge','Creamy') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_chicken_pasta,'en','allergens','<p>Contains wheat and dairy</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

INSERT INTO `products` (`category_id`,`name`,`slug`,`description`,`price`,`images`,`ingredients`,`preparation_minutes`,`available`,`featured`,`badge`,`sort_order`,`allergens`,`dietary`) VALUES (@cat_others,'বোরহানি','borhani','<p>দই, পুদিনা ও মসলায় তৈরি ঐতিহ্যবাহী ঠান্ডা পানীয়।</p>',10000,'[]','<p>দই, পুদিনা, মসলা</p>',5,1,0,'ঠান্ডা পানীয়',23,'<p>দুধ</p>','') ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`category_id`=VALUES(`category_id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`price`=VALUES(`price`),`images`=IF(`products`.`images`='[]' OR `products`.`images`='' ,VALUES(`images`),`products`.`images`),`ingredients`=VALUES(`ingredients`),`preparation_minutes`=VALUES(`preparation_minutes`),`available`=1,`featured`=VALUES(`featured`),`badge`=VALUES(`badge`),`sort_order`=VALUES(`sort_order`),`allergens`=VALUES(`allergens`),`dietary`=VALUES(`dietary`);
SET @prod_borhani=LAST_INSERT_ID();
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_borhani,'en','name','Borhani') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_borhani,'en','description','<p>Traditional yogurt drink flavoured with mint and spices.</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_borhani,'en','ingredients','<p>Yogurt, mint, spices</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_borhani,'en','badge','Cold drink') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_borhani,'en','allergens','<p>Contains dairy</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

INSERT INTO `products` (`category_id`,`name`,`slug`,`description`,`price`,`images`,`ingredients`,`preparation_minutes`,`available`,`featured`,`badge`,`sort_order`,`allergens`,`dietary`) VALUES (@cat_others,'লাচ্ছি','sweet-lassi','<p>দই দিয়ে তৈরি মিষ্টি ও ঠান্ডা লাচ্ছি।</p>',12000,'[]','<p>দই, চিনি, পানি</p>',5,1,0,'ঠান্ডা পানীয়',24,'<p>দুধ</p>','') ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`),`category_id`=VALUES(`category_id`),`name`=VALUES(`name`),`description`=VALUES(`description`),`price`=VALUES(`price`),`images`=IF(`products`.`images`='[]' OR `products`.`images`='' ,VALUES(`images`),`products`.`images`),`ingredients`=VALUES(`ingredients`),`preparation_minutes`=VALUES(`preparation_minutes`),`available`=1,`featured`=VALUES(`featured`),`badge`=VALUES(`badge`),`sort_order`=VALUES(`sort_order`),`allergens`=VALUES(`allergens`),`dietary`=VALUES(`dietary`);
SET @prod_sweet_lassi=LAST_INSERT_ID();
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_sweet_lassi,'en','name','Sweet Lassi') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_sweet_lassi,'en','description','<p>Sweet and refreshing yogurt-based lassi.</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_sweet_lassi,'en','ingredients','<p>Yogurt, sugar, water</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_sweet_lassi,'en','badge','Cold drink') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
INSERT INTO `content_translations` (`entity`,`entity_id`,`locale`,`field`,`value`) VALUES ('products',@prod_sweet_lassi,'en','allergens','<p>Contains dairy</p>') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);

-- Remove old empty demo categories after products have been moved/deleted.
DELETE c FROM `categories` c LEFT JOIN `products` p ON p.`category_id`=c.`id` WHERE c.`slug` IN ('meat','fish') AND p.`id` IS NULL;

COMMIT;

-- Verification query
SELECT p.`id`, c.`name` AS `category`, p.`name`, p.`slug`, ROUND(p.`price`/100,2) AS `price_bdt`, p.`available`, p.`featured` FROM `products` p INNER JOIN `categories` c ON c.`id`=p.`category_id` ORDER BY c.`sort_order`, p.`sort_order`, p.`id`;