<?php
$featured=array_slice(array_values(array_filter($products,fn($p)=>!empty($p['featured']))),0,6);
if(!$featured)$featured=array_slice($products,0,6);
$homeCategory = is_string($_GET['home_category'] ?? null) ? $_GET['home_category'] : '';
$homeCategoryIds = array_column($categories, 'id', 'slug');
if (!isset($homeCategoryIds[$homeCategory])) $homeCategory = '';
if ($homeCategory !== '') $featured = array_values(array_filter($featured, static fn($p) => (int) $p['category_id'] === (int) $homeCategoryIds[$homeCategory]));
?>
<section class="bd-hero bg-[#f8f4eb] text-[#143e31] [&_h1]:[font-size:clamp(40px,4.3vw,64px)] [&_h1]:font-bold [&_h1]:[line-height:1.35] [&_h1]:[letter-spacing:-.025em] [&_h1_span]:block [&_h1_span]:text-[#ae4a28] max-[561px]:[&_h1]:[font-size:42px]">
 <div class="bd-wrap [width:min(1240px,100%_-_40px)] mx-auto max-[561px]:[width:calc(100%_-_32px)] bd-hero-grid grid [grid-template-columns:1fr_1.05fr] [gap:54px] items-center [padding-block:56px_64px] max-[851px]:grid-cols-1 max-[851px]:[gap:28px] max-[851px]:[padding-block:34px]">
  <div class="motion-safe:animate-hero-in">
   <p class="bd-kicker text-[#a34425] text-xs font-bold [letter-spacing:.09em] mb-4"><?= rich_inline(setting('hero.eyebrow')); ?></p>
   <h1 class="font-display [overflow-wrap:anywhere]"><?= rich_inline(setting('hero.title')); ?><span><?= rich_inline(setting('hero.accent')); ?></span></h1>
   <div class="bd-intro [max-width:470px] text-[#4c6056] text-base mt-[22px] [line-height:1.9] max-[851px]:[max-width:none] rich-content [&_.ql-color-red]:text-[#c23935] [&_.ql-color-gold]:text-[#ac853b] [&_.ql-color-green]:text-[#398047] [&_.ql-color-blue]:text-[#2563eb] [&_.ql-color-purple]:text-[#7c3aed] [&_.ql-color-white]:text-[#fff] [&_.ql-color-black]:text-[#111] leading-8 [&_p_+_p]:mt-4 [&_ul]:list-disc [&_ul]:pl-6 [&_ol]:list-decimal [&_ol]:pl-6 [&_blockquote]:my-4 [&_blockquote]:border-l-2 [&_blockquote]:border-accent [&_blockquote]:pl-4 [&_blockquote]:italic [&_strong]:font-bold [&_em]:italic"><?= rich(setting('hero.description')); ?></div>
   <div class="bd-actions flex flex-wrap items-center gap-6 [margin-block:28px] max-[561px]:[gap:15px]"><a href="/menu" class="bd-button inline-flex justify-center items-center gap-6 bg-[#174934] text-white [min-height:50px] [padding:14px_24px] [border-radius:9px] font-semibold [transition:background_.2s] [&:hover]:bg-[#286549] motion-reduce:[transition:none]">খাবার অর্ডার করুন <span aria-hidden="true">↗</span></a><a class="bd-link inline-block text-[#174934] [border-bottom:1px_solid_#839e8c] py-3 font-semibold text-sm" href="/contact#reserve">টেবিল বুকিং →</a></div>
   <form class="bd-search flex [max-width:465px] [border:1px_solid_#d4d9ce] [border-radius:9px] bg-white [padding:5px] [&_input]:border-0 [&_input]:bg-transparent [&_input]:min-w-0 [&_input]:flex-1 [&_button]:bg-[#efe9dc] [&_button]:rounded-md [&_button]:[padding:10px_17px] [&_button]:text-[#173b2b] [&_button]:font-semibold [&_button]:shrink-0" action="/menu" method="get" role="search"><label for="home-search" class="block text-sm font-medium sr-only">পছন্দের খাবার খুঁজুন</label><input class="w-full rounded-lg border border-stone-300 bg-white p-3 text-sm text-ink [&[type=checkbox]]:w-auto [&[type=radio]]:w-auto" id="home-search" name="q" maxlength="100" placeholder="কী খেতে চান? যেমন: কাচ্চি" type="search"><button type="submit">খুঁজুন</button></form>
   <p class="bd-small text-xs [line-height:1.8] text-[#65736a] mt-3.5">ডেলিভারি ও পিকআপ · মূল্য বাংলাদেশি টাকায়</p>
  </div>
  <figure class="bd-hero-photo m-0 relative rounded-3xl overflow-hidden bg-[#e2d2b5] [box-shadow:0_18px_50px_#263d2412] [&_img]:w-full [&_img]:[height:480px] [&_img]:object-cover [&_figcaption]:flex [&_figcaption]:justify-between [&_figcaption]:gap-4 [&_figcaption]:absolute [&_figcaption]:bottom-0 [&_figcaption]:left-0 [&_figcaption]:right-0 [&_figcaption]:bg-[#153b2bef] [&_figcaption]:text-white [&_figcaption]:p-5 [&_figcaption]:text-sm [&_figcaption_a]:text-[#f4d3a0] max-[851px]:[&_img]:[height:330px] max-[561px]:[&_img]:[height:285px] max-[561px]:[&_figcaption]:text-xs max-[561px]:[&_figcaption]:[padding:15px]"><img src="<?= e(safeImage(setting('hero.image'))); ?>" alt="দেশি ভোজের খাবারের আয়োজন" width="1536" height="1024" fetchpriority="high"><figcaption><span>ঘরোয়া স্বাদের আয়োজন</span><a href="/menu">মেনু দেখুন ↗</a></figcaption></figure>
 </div>
</section>
<section class="bd-service bg-white [border-block:1px_solid_#e7e8dd] [&_strong]:text-[#224b36] [&_strong]:[font-size:15px] [&_span]:text-[#667067] [&_span]:text-xs" aria-label="অর্ডারের তথ্য"><div class="bd-wrap [width:min(1240px,100%_-_40px)] mx-auto max-[561px]:[width:calc(100%_-_32px)] bd-service-grid grid grid-cols-3 [padding-block:23px] gap-6 [&>div]:flex [&>div]:flex-col [&>div]:gap-1.5 [&>div]:pl-[18px] [&>div]:[border-left:2px_solid_#dba86f] max-[851px]:[gap:14px] max-[561px]:grid-cols-1 max-[561px]:[padding-block:20px] max-[561px]:gap-4 max-[561px]:[&>div]:flex-row max-[561px]:[&>div]:flex-wrap max-[561px]:[&>div]:[gap:7px_16px]"><div><strong>পিকআপ</strong><span>আনুমানিক <?= e(setting('ordering.pickup_time')); ?></span></div><div><strong>হোম ডেলিভারি</strong><span>আনুমানিক <?= e(setting('ordering.delivery_time')); ?></span></div><div><strong>সহজ পেমেন্ট</strong><span>নগদ · অনলাইন চালু থাকলে bKash / Nagad</span></div></div></section>
<section class="bd-wrap [width:min(1240px,100%_-_40px)] mx-auto max-[561px]:[width:calc(100%_-_32px)] bd-menu py-16 [&_article_h3]:[font-size:23px] [&_article_h3]:font-semibold [&_article_h3]:[line-height:1.5] [&_.btn-dark]:bg-[#174934] [&_article_.text-stone-500]:text-[#58665d] max-[851px]:py-[42px]" id="home-menu" aria-labelledby="food-heading">
 <div class="bd-section-head flex justify-between items-end gap-6 [margin-bottom:26px] [&_h2]:font-semibold [&_h2]:[font-size:clamp(27px,3vw,39px)] [&_h2]:[line-height:1.5] [&_h2]:[margin-bottom:12px] [&_h2]:text-[#173d2e] max-[851px]:items-start max-[851px]:flex-col"><div><p class="bd-kicker text-[#a34425] text-xs font-bold [letter-spacing:.09em] mb-4">আমাদের মেনু</p><h2 class="font-display [overflow-wrap:anywhere]" id="food-heading"><?= rich_inline(setting('home.menu_title')); ?></h2><div class="rich-content [&_.ql-color-red]:text-[#c23935] [&_.ql-color-gold]:text-[#ac853b] [&_.ql-color-green]:text-[#398047] [&_.ql-color-blue]:text-[#2563eb] [&_.ql-color-purple]:text-[#7c3aed] [&_.ql-color-white]:text-[#fff] [&_.ql-color-black]:text-[#111] leading-8 [&_p_+_p]:mt-4 [&_ul]:list-disc [&_ul]:pl-6 [&_ol]:list-decimal [&_ol]:pl-6 [&_blockquote]:my-4 [&_blockquote]:border-l-2 [&_blockquote]:border-accent [&_blockquote]:pl-4 [&_blockquote]:italic [&_strong]:font-bold [&_em]:italic bd-muted text-[#607064] [font-size:15px] [line-height:1.9]"><?= rich(setting('home.menu_description')); ?></div></div><a class="bd-link inline-block text-[#174934] [border-bottom:1px_solid_#839e8c] py-3 font-semibold text-sm" href="/menu">সব খাবার দেখুন →</a></div>
 <nav class="mb-7 flex gap-2 overflow-x-auto rounded-2xl bg-[#153e2e] p-2 text-sm text-paper sm:flex-wrap" aria-label="খাবারের বিভাগ" data-home-categories>
 <?php $homeLinks = [['slug' => '', 'name' => 'সব খাবার'], ...$categories]; foreach ($homeLinks as $category): ?>
 <a class="shrink-0 rounded-full px-5 py-3 font-medium hover:bg-white/10 aria-[current=page]:bg-[#d8c6a2] aria-[current=page]:text-[#153e2e]" href="/?<?= e(http_build_query(['home_category' => $category['slug'], 'lang' => App\Services\Locale::current()])); ?>#home-menu" <?= $homeCategory === $category['slug'] ? 'aria-current="page"' : ''; ?>><?= e(plain($category['name'])); ?></a>
 <?php endforeach; ?>
 </nav>
 <?php $products=$featured;require __DIR__.'/cards.php'; ?>
</section>
<section class="bd-story [&_h2]:font-semibold [&_h2]:[font-size:clamp(27px,3vw,39px)] [&_h2]:[line-height:1.5] [&_h2]:[margin-bottom:12px] [&_h2]:text-[#173d2e] bg-[#ebeede] [padding-block:54px] [&_img]:[border-radius:18px] [&_img]:aspect-[4/3] [&_img]:w-full [&_img]:object-cover [&_.bd-link]:mt-[22px] max-[561px]:[padding-block:36px]"><div class="bd-wrap [width:min(1240px,100%_-_40px)] mx-auto max-[561px]:[width:calc(100%_-_32px)] bd-story-grid grid grid-cols-2 [gap:60px] items-center max-[851px]:[gap:25px] max-[561px]:grid-cols-1"><img src="<?= e(safeImage(setting('about.image'))); ?>" alt="বাংলাদেশি খাবারের আয়োজন" loading="lazy" width="1536" height="1024"><div><p class="bd-kicker text-[#a34425] text-xs font-bold [letter-spacing:.09em] mb-4">শেকড়ের স্বাদ</p><h2 class="font-display [overflow-wrap:anywhere]"><?= rich_inline(setting('about.title')); ?></h2><div class="rich-content [&_.ql-color-red]:text-[#c23935] [&_.ql-color-gold]:text-[#ac853b] [&_.ql-color-green]:text-[#398047] [&_.ql-color-blue]:text-[#2563eb] [&_.ql-color-purple]:text-[#7c3aed] [&_.ql-color-white]:text-[#fff] [&_.ql-color-black]:text-[#111] leading-8 [&_p_+_p]:mt-4 [&_ul]:list-disc [&_ul]:pl-6 [&_ol]:list-decimal [&_ol]:pl-6 [&_blockquote]:my-4 [&_blockquote]:border-l-2 [&_blockquote]:border-accent [&_blockquote]:pl-4 [&_blockquote]:italic [&_strong]:font-bold [&_em]:italic bd-muted text-[#607064] [font-size:15px] [line-height:1.9]"><?= rich(setting('about.description')); ?></div><a class="bd-link inline-block text-[#174934] [border-bottom:1px_solid_#839e8c] py-3 font-semibold text-sm" href="/about">আমাদের গল্প পড়ুন →</a></div></div></section>
<section class="bd-wrap [width:min(1240px,100%_-_40px)] mx-auto max-[561px]:[width:calc(100%_-_32px)] bd-how py-16 [&_article]:[border-top:1px_solid_#cfdbcf] [&_article]:[padding-top:20px] [&_article>span]:text-[32px] [&_article>span]:text-[#ac542e] [&_h3]:text-xl [&_h3]:font-semibold [&_h3]:[margin-block:12px] [&_p]:text-sm [&_p]:[line-height:1.9] [&_p]:text-[#627166] max-[851px]:py-[42px] max-[561px]:[&_article]:[padding-top:15px]"><div class="bd-section-head flex justify-between items-end gap-6 [margin-bottom:26px] [&_h2]:font-semibold [&_h2]:[font-size:clamp(27px,3vw,39px)] [&_h2]:[line-height:1.5] [&_h2]:[margin-bottom:12px] [&_h2]:text-[#173d2e] max-[851px]:items-start max-[851px]:flex-col"><div><p class="bd-kicker text-[#a34425] text-xs font-bold [letter-spacing:.09em] mb-4">তিন ধাপেই অর্ডার</p><h2 class="font-display [overflow-wrap:anywhere]">পছন্দ থেকে আপনার টেবিলে।</h2></div></div><div class="bd-how-grid grid grid-cols-3 gap-6 max-[851px]:[gap:18px] max-[561px]:grid-cols-1"><?php foreach([['01','খাবার বেছে নিন','মেনু থেকে পছন্দের পদ ও পরিমাণ cart-এ যোগ করুন।'],['02','ঠিকানা ও পেমেন্ট','ডেলিভারি বা পিকআপ বেছে অর্ডারের তথ্য দিন।'],['03','নিশ্চিতকরণের অপেক্ষা','অর্ডার পাতায় অবস্থা দেখুন। প্রয়োজনে আমাদের দল যোগাযোগ করবে।']] as [$number,$heading,$copy]): ?><article><span><?= $number; ?></span><h3 class="font-display [overflow-wrap:anywhere]"><?= $heading; ?></h3><p><?= $copy; ?></p></article><?php endforeach; ?></div></section>
<?php if($reviews): ?><section class="bd-wrap [width:min(1240px,100%_-_40px)] mx-auto max-[561px]:[width:calc(100%_-_32px)] bd-reviews py-16 [&_h2]:font-semibold [&_h2]:[font-size:clamp(27px,3vw,39px)] [&_h2]:[line-height:1.5] [&_h2]:[margin-bottom:12px] [&_h2]:text-[#173d2e]"><h2 class="font-display [overflow-wrap:anywhere]">অতিথিদের কথা</h2><div class="bd-how-grid grid grid-cols-3 gap-6 max-[851px]:[gap:18px] max-[561px]:grid-cols-1"><?php foreach(array_slice($reviews,0,3) as $r): ?><blockquote class="card rounded-2xl border border-stone-200 bg-white p-6 shadow-sm"><p aria-label="<?= (int)$r['rating']; ?> out of 5"><?= str_repeat('★',max(0,min(5,(int)$r['rating']))); ?></p><div class="rich-content [&_.ql-color-red]:text-[#c23935] [&_.ql-color-gold]:text-[#ac853b] [&_.ql-color-green]:text-[#398047] [&_.ql-color-blue]:text-[#2563eb] [&_.ql-color-purple]:text-[#7c3aed] [&_.ql-color-white]:text-[#fff] [&_.ql-color-black]:text-[#111] leading-8 [&_p_+_p]:mt-4 [&_ul]:list-disc [&_ul]:pl-6 [&_ol]:list-decimal [&_ol]:pl-6 [&_blockquote]:my-4 [&_blockquote]:border-l-2 [&_blockquote]:border-accent [&_blockquote]:pl-4 [&_blockquote]:italic [&_strong]:font-bold [&_em]:italic"><?= rich($r['comment']); ?></div><cite><?= e(plain($r['name'])); ?></cite></blockquote><?php endforeach; ?></div></section><?php endif; ?>
<section class="bd-reserve [&_h2]:font-semibold [&_h2]:[font-size:clamp(27px,3vw,39px)] [&_h2]:[line-height:1.5] [&_h2]:[margin-bottom:12px] bg-[#163e2d] text-[#e4eade] text-center [padding-block:62px] [&_h2]:text-white [&_.bd-kicker]:text-[#edc493] [&_.rich-content]:[max-width:590px] [&_.rich-content]:[margin:0_auto] [&_.bd-button]:bg-[#edca91] [&_.bd-button]:text-[#173d2e] [&_.bd-button]:[margin-top:26px] [&_.bd-small]:text-[#b6c4b5] max-[561px]:[padding-block:44px]"><div class="bd-wrap [width:min(1240px,100%_-_40px)] mx-auto max-[561px]:[width:calc(100%_-_32px)]"><p class="bd-kicker text-[#a34425] text-xs font-bold [letter-spacing:.09em] mb-4">একসঙ্গে খাওয়ার আনন্দ</p><h2 class="font-display [overflow-wrap:anywhere]"><?= rich_inline(setting('home.reserve_title')); ?></h2><div class="rich-content [&_.ql-color-red]:text-[#c23935] [&_.ql-color-gold]:text-[#ac853b] [&_.ql-color-green]:text-[#398047] [&_.ql-color-blue]:text-[#2563eb] [&_.ql-color-purple]:text-[#7c3aed] [&_.ql-color-white]:text-[#fff] [&_.ql-color-black]:text-[#111] leading-8 [&_p_+_p]:mt-4 [&_ul]:list-disc [&_ul]:pl-6 [&_ol]:list-decimal [&_ol]:pl-6 [&_blockquote]:my-4 [&_blockquote]:border-l-2 [&_blockquote]:border-accent [&_blockquote]:pl-4 [&_blockquote]:italic [&_strong]:font-bold [&_em]:italic"><?= rich(setting('home.reserve_description')); ?></div><a class="bd-button inline-flex justify-center items-center gap-6 bg-[#174934] text-white [min-height:50px] [padding:14px_24px] [border-radius:9px] font-semibold [transition:background_.2s] [&:hover]:bg-[#286549] motion-reduce:[transition:none]" href="/contact#reserve">টেবিলের অনুরোধ পাঠান ↗</a><p class="bd-small text-xs [line-height:1.8] text-[#65736a] mt-3.5">রেস্টুরেন্টের নিশ্চিতকরণের পর বুকিং চূড়ান্ত হবে।</p></div></section>
